### PR TITLE
Add serial number field (2.5.4.5)

### PR DESCRIPTION
**Pull request by Stoexn**
Add the possibility to set the serial number field (2.5.4.5) in the subject

### CODE REVIEW

**Comment by cbaker6** [comment]
Thanks for your addition. Can you add a test case for this to ensure it break in the future?

**Comment by Mastoktm** [comment]
I added unit tests for the convenience init methods to increase the code coverage

**Comment by thannerfabian** [comment]
Hello @cbaker6,
is the tests, that @Mastoktm provided enough to complete this PR, because I would need this feature.
Thank you!

**Review by cbaker6 — APPROVED** [review]
LGTM!

**Pull request merged**
